# qualifilter_config.yaml
# Optional user config for QualiFilter
# Overrides default allowed columns and rename map

ALLOWED_COLUMNS:
  - Sample
  - Total_reads
  - Mapped_reads
  - Mapping_pct
  - Median_depth
  - Coverage_gte_10x_pct
  - GC_pct
  - Kraken_top1_pct
  - Kraken_unclassified_pct
  - Contam_pct
  - QC_status
  - Total_reads_pass
  - Coverage_gte_10x_pct_pass
  - Contam_pct_pass
  

RENAME_MAP:
  qualimap_bamqc-total_reads: Total_reads
  qualimap_bamqc-mapped_reads: Mapped_reads
  qualimap_bamqc-percentage_aligned: Mapping_pct
  qualimap_bamqc-median_coverage: Median_depth
  qualimap_bamqc-10_x_pc: Coverage_gte_10x_pct
  qualimap_bamqc-avg_gc: GC_pct
  kraken-pct_top_one: Kraken_top1_pct
  kraken-pct_unclassified: Kraken_unclassified_pct
